# Generated by Django 6.0.6 on 2026-07-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('post_body', models.TextField()),
                ('created_date', models.DateField()),
            ],
        ),
    ]
